// stage 2/ticket-app-react/components/navigation.tsx
"use client"

import Link from "next/link"
import { Button } from "@/components/ui/button"
import { useRouter, usePathname } from "next/navigation"
import { useEffect, useState } from "react"

export function Navigation() {
  const router = useRouter()
  const pathname = usePathname()
  const [isLoggedIn, setIsLoggedIn] = useState(false)
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
    const user = localStorage.getItem("user")
    setIsLoggedIn(!!user)
  }, [pathname])

  const handleLogout = () => {
    localStorage.removeItem("user")
    setIsLoggedIn(false)
    router.push("/")
  }

  if (!mounted) return null

  return (
    <nav className="border-b border-border bg-card sticky top-0 z-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex items-center justify-between">
        <Link href="/" className="text-2xl font-bold text-foreground">
          TicketFlow
        </Link>

        <div className="flex items-center gap-4">
          {isLoggedIn ? (
            <>
              <Link href="/dashboard">
                <Button variant={pathname === "/dashboard" ? "default" : "ghost"}>Dashboard</Button>
              </Link>
              <Button variant="outline" onClick={handleLogout}>
                Logout
              </Button>
            </>
          ) : (
            <>
              <Link href="/login">
                <Button variant={pathname === "/login" ? "default" : "ghost"}>Login</Button>
              </Link>
              <Link href="/signup">
                <Button variant={pathname === "/signup" ? "default" : "default"}>Sign Up</Button>
              </Link>
            </>
          )}
        </div>
      </div>
    </nav>
  )
}

// stage 2/vue-ticket-app/src/components/Navigation.vue
<!-- eslint-disable vue/no-setup-props-destructure -->
<template>
  <nav class="sticky top-0 z-50 bg-white border-b border-gray-200 shadow-sm">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex justify-between items-center h-16">
        <router-link to="/" class="flex items-center gap-2">
          <div class="w-8 h-8 bg-purple-600 rounded-lg flex items-center justify-center">
            <span class="text-white font-bold text-lg">T</span>
          </div>
          <span class="font-bold text-lg text-gray-900">TicketHub</span>
        </router-link>
        
        <div class="flex items-center gap-4">
          <router-link 
            v-if="!isAuthenticated" 
            to="/login" 
            class="px-4 py-2 text-gray-700 hover:text-gray-900 font-medium"
          >
            Login
          </router-link>
          <router-link 
            v-if="!isAuthenticated" 
            to="/signup" 
            class="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 font-medium"
          >
            Sign Up
          </router-link>
          <router-link 
            v-if="isAuthenticated" 
            to="/dashboard" 
            class="px-4 py-2 text-gray-700 hover:text-gray-900 font-medium"
          >
            Dashboard
          </router-link>
          <button 
            v-if="isAuthenticated" 
            @click="logout"
            class="px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 font-medium"
          >
            Logout
          </button>
        </div>
      </div>
    </div>
  </nav>
</template>

<script setup>
import { computed } from 'vue'
import { useRouter } from 'vue-router'

const router = useRouter()

const isAuthenticated = computed(() => {
  return !!localStorage.getItem('currentUser')
})

const logout = () => {
  localStorage.removeItem('currentUser')
  router.push('/')
}
</script>
