// stage 2/vue-ticket-app/src/components/HeroSection.vue
<template>
  <section class="relative overflow-hidden bg-white pt-20 pb-32">
    <!-- Wavy SVG Background -->
    <svg class="absolute inset-0 w-full h-full" viewBox="0 0 1440 600" preserveAspectRatio="none">
      <defs>
        <linearGradient id="waveGradient" x1="0%" y1="0%" x2="0%" y2="100%">
          <stop offset="0%" style="stop-color:#f3f4f6;stop-opacity:1" />
          <stop offset="100%" style="stop-color:#e5e7eb;stop-opacity:1" />
        </linearGradient>
      </defs>
      <path d="M0,200 Q360,100 720,200 T1440,200 L1440,600 L0,600 Z" fill="url(#waveGradient)" />
    </svg>
    
    <!-- Decorative Circles -->
    <div class="absolute top-20 right-10 w-72 h-72 bg-purple-200 rounded-full opacity-20 blur-3xl"></div>
    <div class="absolute bottom-0 left-10 w-96 h-96 bg-blue-200 rounded-full opacity-20 blur-3xl"></div>
    
    <!-- Content -->
    <div class="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="grid md:grid-cols-2 gap-12 items-center">
        <div>
          <h1 class="text-5xl md:text-6xl font-bold text-gray-900 mb-6 leading-tight">
            Manage Your Tickets with <span class="text-purple-600">Ease</span>
          </h1>
          <p class="text-xl text-gray-600 mb-8 leading-relaxed">
            TicketHub is your all-in-one solution for ticket management. Create, track, and resolve tickets efficiently with our intuitive platform.
          </p>
          <div class="flex gap-4">
            <router-link 
              to="/signup" 
              class="px-8 py-3 bg-purple-600 text-white rounded-lg font-bold hover:bg-purple-700 transition"
            >
              Get Started
            </router-link>
            <router-link 
              to="/login" 
              class="px-8 py-3 border-2 border-purple-600 text-purple-600 rounded-lg font-bold hover:bg-purple-50 transition"
            >
              Sign In
            </router-link>
          </div>
        </div>
        
        <div class="relative">
          <div class="bg-gradient-to-br from-purple-100 to-blue-100 rounded-2xl p-8 shadow-lg">
            <div class="space-y-4">
              <div class="bg-white p-4 rounded-lg shadow-sm">
                <div class="flex items-center gap-3">
                  <div class="w-3 h-3 bg-green-500 rounded-full"></div>
                  <span class="text-sm font-medium text-gray-700">Open Tickets: 12</span>
                </div>
              </div>
              <div class="bg-white p-4 rounded-lg shadow-sm">
                <div class="flex items-center gap-3">
                  <div class="w-3 h-3 bg-amber-500 rounded-full"></div>
                  <span class="text-sm font-medium text-gray-700">In Progress: 8</span>
                </div>
              </div>
              <div class="bg-white p-4 rounded-lg shadow-sm">
                <div class="flex items-center gap-3">
                  <div class="w-3 h-3 bg-gray-500 rounded-full"></div>
                  <span class="text-sm font-medium text-gray-700">Closed: 45</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

// stage 2/ticket-app-react/components/hero-section.tsx
"use client"

import Link from "next/link"
import { Button } from "@/components/ui/button"

export function HeroSection() {
  return (
    <section className="relative overflow-hidden py-20 sm:py-32 px-4 sm:px-6 lg:px-8">
      <svg
        className="absolute inset-0 w-full h-full"
        viewBox="0 0 1440 800"
        preserveAspectRatio="none"
        style={{ zIndex: -1 }}
      >
        <defs>
          <linearGradient id="waveGradient" x1="0%" y1="0%" x2="0%" y2="100%">
            <stop offset="0%" stopColor="var(--color-primary)" stopOpacity="0.1" />
            <stop offset="100%" stopColor="var(--color-primary)" stopOpacity="0.05" />
          </linearGradient>
        </defs>
        <path d="M0,400 Q360,300 720,400 T1440,400 L1440,800 L0,800 Z" fill="url(#waveGradient)" />
        <path d="M0,500 Q360,400 720,500 T1440,500 L1440,800 L0,800 Z" fill="var(--color-primary)" opacity="0.05" />
      </svg>

      {/* Decorative circles */}
      <div className="absolute top-20 right-10 w-72 h-72 rounded-full bg-primary/5 blur-3xl" />
      <div className="absolute bottom-0 left-10 w-96 h-96 rounded-full bg-primary/5 blur-3xl" />

      <div className="max-w-7xl mx-auto relative z-10">
        <div className="text-center">
          <div className="inline-block mb-6 px-4 py-2 rounded-full bg-primary/10 border border-primary/20">
            <p className="text-sm font-medium text-primary">Welcome to TicketFlow</p>
          </div>

          <h1 className="text-5xl sm:text-6xl lg:text-7xl font-bold text-foreground mb-6 text-balance">
            Manage Your Tickets with Ease
          </h1>

          <p className="text-xl text-muted-foreground mb-8 max-w-2xl mx-auto text-balance">
            A powerful ticket management system designed to streamline your workflow and boost productivity
          </p>

          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link href="/signup">
              <Button size="lg" className="w-full sm:w-auto">
                Get Started Free
              </Button>
            </Link>
            <Link href="/login">
              <Button size="lg" variant="outline" className="w-full sm:w-auto bg-transparent">
                Sign In
              </Button>
            </Link>
          </div>
        </div>
      </div>
    </section>
  )
}
